export const countries = [
  { index: "AFG", value: "Afghanistan" },
  { index: "ALB", value: "Albania" },
  { index: "ALG", value: "Algeria" },
  { index: "AND", value: "Andorra" },
  { index: "ANG", value: "Angola" },
  { index: "ANT", value: "Antigua and Barbuda" },
  { index: "ARG", value: "Argentina" },
  { index: "ARM", value: "Armenia" },
  { index: "ARU", value: "Aruba" },
  { index: "ASA", value: "American Samoa" },
  { index: "AUS", value: "Australia" },
  { index: "AUT", value: "Austria" },
  { index: "AZE", value: "Azerbaijan" },
  { index: "BAH", value: "Bahamas" },
  { index: "BAN", value: "Bangladesh" },
  { index: "BAR", value: "Barbados" },
  { index: "BDI", value: "Burundi" },
  { index: "BEL", value: "Belgium" },
  { index: "BEN", value: "Benin" },
  { index: "BER", value: "Bermuda" },
  { index: "BHU", value: "Bhutan" },
  { index: "BIH", value: "Bosnia and Herzegovina" },
  { index: "BIZ", value: "Belize" },
  { index: "BLR", value: "Belarus" },
  { index: "BOL", value: "Bolivia" },
  { index: "BOT", value: "Botswana" },
  { index: "BRA", value: "Brazil" },
  { index: "BRN", value: "Bahrain" },
  { index: "BRU", value: "Brunei" },
  { index: "BUL", value: "Bulgaria" },
  { index: "BUR", value: "Burkina Faso" },
  { index: "CAF", value: "Central African Republic" },
  { index: "CAM", value: "Cambodia" },
  { index: "CAN", value: "Canada" },
  { index: "CAY", value: "Cayman Islands" },
  { index: "CGO", value: "Congo" },
  { index: "CHA", value: "Chad" },
  { index: "CHI", value: "Chile" },
  { index: "CHN", value: "China" },
  { index: "CIV", value: "Cote d'Ivoire" },
  { index: "CMR", value: "Cameroon" },
  { index: "COD", value: "DR Congo" },
  { index: "COK", value: "Cook Islands" },
  { index: "COL", value: "Colombia" },
  { index: "COM", value: "Comoros" },
  { index: "CPV", value: "Cape Verde" },
  { index: "CRC", value: "Costa Rica" },
  { index: "CRO", value: "Croatia" },
  { index: "CUB", value: "Cuba" },
  { index: "CYP", value: "Cyprus" },
  { index: "CZE", value: "Czech Republic" },
  { index: "DEN", value: "Denmark" },
  { index: "DJI", value: "Djibouti" },
  { index: "DMA", value: "Dominica" },
  { index: "DOM", value: "Dominican Republic" },
  { index: "ECU", value: "Ecuador" },
  { index: "EGY", value: "Egypt" },
  { index: "ERI", value: "Eritrea" },
  { index: "ESA", value: "El Salvador" },
  { index: "ESP", value: "Spain" },
  { index: "EST", value: "Estonia" },
  { index: "ETH", value: "Ethiopia" },
  { index: "FIJ", value: "Fiji" },
  { index: "FIN", value: "Finland" },
  { index: "FRA", value: "France" },
  { index: "FSM", value: "Micronesia" },
  { index: "GAB", value: "Gabon" },
  { index: "GAM", value: "Gambia" },
  { index: "GBR", value: "Great Britain" },
  { index: "GBS", value: "Guinea-Bissau" },
  { index: "GEO", value: "Georgia" },
  { index: "GEQ", value: "Equatorial Guinea" },
  { index: "GER", value: "Germany" },
  { index: "GHA", value: "Ghana" },
  { index: "GRE", value: "Greece" },
  { index: "GRN", value: "Grenada" },
  { index: "GUA", value: "Guatemala" },
  { index: "GUI", value: "Guinea" },
  { index: "GUM", value: "Guam" },
  { index: "GUY", value: "Guyana" },
  { index: "HAI", value: "Haiti" },
  { index: "HKG", value: "Hong Kong" },
  { index: "HON", value: "Honduras" },
  { index: "HUN", value: "Hungary" },
  { index: "INA", value: "Indonesia" },
  { index: "IND", value: "India" },
  { index: "IRI", value: "Iran" },
  { index: "IRL", value: "Ireland" },
  { index: "IRQ", value: "Iraq" },
  { index: "ISL", value: "Iceland" },
  { index: "ISR", value: "Israel" },
  { index: "ISV", value: "Virgin Islands" },
  { index: "ITA", value: "Italy" },
  { index: "IVB", value: "British Virgin Islands" },
  { index: "JAM", value: "Jamaica" },
  { index: "JOR", value: "Jordan" },
  { index: "JPN", value: "Japan" },
  { index: "KAZ", value: "Kazakhstan" },
  { index: "KEN", value: "Kenya" },
  { index: "KGZ", value: "Kyrgyzstan" },
  { index: "KIR", value: "Kiribati" },
  { index: "KOR", value: "South Korea" },
  { index: "KOS", value: "Kosovo" },
  { index: "KSA", value: "Saudi Arabia" },
  { index: "KUW", value: "Kuwait" },
  { index: "LAO", value: "Laos" },
  { index: "LAT", value: "Latvia" },
  { index: "LBA", value: "Libya" },
  { index: "LBR", value: "Liberia" },
  { index: "LCA", value: "Saint Lucia" },
  { index: "LES", value: "Lesotho" },
  { index: "LIB", value: "Lebanon" },
  { index: "LIE", value: "Liechtenstein" },
  { index: "LTU", value: "Lithuania" },
  { index: "LUX", value: "Luxembourg" },
  { index: "MAD", value: "Madagascar" },
  { index: "MAR", value: "Morocco" },
  { index: "MAS", value: "Malaysia" },
  { index: "MAW", value: "Malawi" },
  { index: "MDA", value: "Moldova" },
  { index: "MDV", value: "Maldives" },
  { index: "MEX", value: "Mexico" },
  { index: "MGL", value: "Mongolia" },
  { index: "MHL", value: "Marshall Islands" },
  { index: "MKD", value: "Macedonia" },
  { index: "MLI", value: "Mali" },
  { index: "MLT", value: "Malta" },
  { index: "MNE", value: "Montenegro" },
  { index: "MON", value: "Monaco" },
  { index: "MOZ", value: "Mozambique" },
  { index: "MRI", value: "Mauritius" },
  { index: "MTN", value: "Mauritania" },
  { index: "MYA", value: "Myanmar" },
  { index: "NAM", value: "Namibia" },
  { index: "NCA", value: "Nicaragua" },
  { index: "NED", value: "Netherlands" },
  { index: "NEP", value: "Nepal" },
  { index: "NGR", value: "Nigeria" },
  { index: "NIG", value: "Niger" },
  { index: "NOR", value: "Norway" },
  { index: "NRU", value: "Nauru" },
  { index: "NZL", value: "New Zealand" },
  { index: "OMA", value: "Oman" },
  { index: "PAK", value: "Pakistan" },
  { index: "PAN", value: "Panama" },
  { index: "PAR", value: "Paraguay" },
  { index: "PER", value: "Peru" },
  { index: "PHI", value: "Philippines" },
  { index: "PLE", value: "Palestine" },
  { index: "PLW", value: "Palau" },
  { index: "PNG", value: "Papua New Guinea" },
  { index: "POL", value: "Poland" },
  { index: "POR", value: "Portugal" },
  { index: "PRK", value: "North Korea" },
  { index: "PUR", value: "Puerto Rico" },
  { index: "QAT", value: "Qatar" },
  { index: "ROU", value: "Romania" },
  { index: "RSA", value: "South Africa" },
  { index: "RUS", value: "Russia" },
  { index: "RWA", value: "Rwanda" },
  { index: "SAM", value: "Samoa" },
  { index: "SEN", value: "Senegal" },
  { index: "SEY", value: "Seychelles" },
  { index: "SIN", value: "Singapore" },
  { index: "SKN", value: "Saint Kitts and Nevis" },
  { index: "SLE", value: "Sierra Leone" },
  { index: "SLO", value: "Slovenia" },
  { index: "SMR", value: "San Marino" },
  { index: "SOL", value: "Solomon Islands" },
  { index: "SOM", value: "Somalia" },
  { index: "SRB", value: "Serbia" },
  { index: "SRI", value: "Sri Lanka" },
  { index: "SSD", value: "South Sudan" },
  { index: "STP", value: "Sao Tome and Principe" },
  { index: "SUD", value: "Sudan" },
  { index: "SUI", value: "Switzerland" },
  { index: "SUR", value: "Suriname" },
  { index: "SVK", value: "Slovakia" },
  { index: "SWE", value: "Sweden" },
  { index: "SWZ", value: "Swaziland" },
  { index: "SYR", value: "Syria" },
  { index: "TAN", value: "Tanzania" },
  { index: "TGA", value: "Tonga" },
  { index: "THA", value: "Thailand" },
  { index: "TJK", value: "Tajikistan" },
  { index: "TKM", value: "Turkmenistan" },
  { index: "TLS", value: "Timor-Leste" },
  { index: "TOG", value: "Togo" },
  { index: "TPE", value: "Chinese Taipei" },
  { index: "TTO", value: "Trinidad and Tobago" },
  { index: "TUN", value: "Tunisia" },
  { index: "TUR", value: "Turkey" },
  { index: "TUV", value: "Tuvalu" },
  { index: "UAE", value: "United Arab Emirates" },
  { index: "UGA", value: "Uganda" },
  { index: "UKR", value: "Ukraine" },
  { index: "URU", value: "Uruguay" },
  { index: "USA", value: "United States" },
  { index: "UZB", value: "Uzbekistan" },
  { index: "VAN", value: "Vanuatu" },
  { index: "VEN", value: "Venezuela" },
  { index: "VIE", value: "Vietnam" },
  { index: "VIN", value: "Saint Vincent and the Grenadines" },
  { index: "YEM", value: "Yemen" },
  { index: "ZAM", value: "Zambia" },
  { index: "ZAN", value: "Zanzibar" },
  { index: "ZIM", value: "Zimbabwe" }
];
